# Generated by Django 4.2.5 on 2023-09-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecetasMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_platos', models.CharField(max_length=20)),
                ('ingredientes', models.CharField(max_length=100)),
                ('receta', models.CharField(max_length=100)),
                ('tiempo', models.IntegerField()),
                ('dificultad', models.CharField(max_length=10)),
                ('tipoDeCocina', models.CharField(max_length=20)),
                ('fuente', models.CharField(max_length=30)),
                ('procedimiento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecetasUsr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_platosUsr', models.CharField(max_length=20)),
                ('ingredientesUsr', models.CharField(max_length=100)),
                ('recetaUsr', models.CharField(max_length=100)),
                ('tiempoUsr', models.IntegerField()),
                ('dificultadUsr', models.CharField(max_length=10)),
                ('tipoDeCocinaUsr', models.CharField(max_length=20)),
                ('fuenteUsr', models.CharField(max_length=30)),
                ('procedimientoUsr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsr', models.CharField(max_length=20)),
                ('emailUsr', models.EmailField(max_length=254)),
                ('telfonoUsr', models.IntegerField()),
                ('ciudad', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
