# Generated by Django 4.2.5 on 2023-10-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsr', models.CharField(max_length=20)),
                ('emailUsr', models.EmailField(max_length=254)),
                ('telfonoUsr', models.IntegerField()),
                ('ciudad', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('tipoDeCocina', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
