# Generated by Django 4.2.5 on 2023-11-07 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppRecetas', '0004_alter_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetasmain',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
