# Generated by Django 4.2.5 on 2023-11-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0007_rename_user_recetasmain_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetasmain',
            name='autor',
        ),
    ]
