# Generated by Django 4.2.5 on 2026-01-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0008_remove_recetasmain_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetasmain',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas'),
        ),
        migrations.AddField(
            model_name='recetasusr',
            name='imagenUsr',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_usuarios'),
        ),
    ]
