# Generated by Django 4.2.5 on 2023-11-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0009_recetasmain_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetasmain',
            old_name='user',
            new_name='usuario',
        ),
    ]
