# Generated by Django 4.2.5 on 2026-01-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0009_recetasmain_imagen_recetasusr_imagenusr'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
