# Generated by Django 4.2.5 on 2026-01-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0010_avatar_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
