# Generated by Django 5.1.6 on 2026-09-09 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0011_alter_avatar_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientePrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('unidad_base', models.CharField(choices=[('g', 'gramos (g)'), ('kg', 'kilos (kg)'), ('ml', 'mililitros (ml)'), ('l', 'litros (l)'), ('unidad', 'unidades'), ('taza', 'tazas'), ('cda', 'cucharadas'), ('cdta', 'cucharaditas'), ('pizca', 'pizcas')], default='unidad', max_length=10)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moneda', models.CharField(default='ARS', max_length=5)),
                ('fuente', models.CharField(blank=True, default='', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recetasmain',
            name='dificultad',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIA', 'Media'), ('DIFICIL', 'Difícil')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='recetasusr',
            name='dificultadUsr',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIA', 'Media'), ('DIFICIL', 'Difícil')], default='MEDIA', max_length=10),
        ),
        migrations.CreateModel(
            name='PasoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('texto', models.TextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='AppRecetas.recetasmain')),
            ],
            options={
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('receta', 'orden'), name='uniq_pasomain_receta_orden')],
            },
        ),
        migrations.CreateModel(
            name='PasoUsr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('texto', models.TextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='AppRecetas.recetasusr')),
            ],
            options={
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('receta', 'orden'), name='uniq_pasousr_receta_orden')],
            },
        ),
    ]
