# Generated by Django 5.1.6 on 2026-09-09 23:24

from django.db import migrations


def normalizar(valor):
    import unicodedata
    v = (valor or "").strip().lower()
    v = "".join(c for c in unicodedata.normalize("NFD", v) if unicodedata.category(c) != "Mn")
    if v in ("facil", "baja", "bajo", "poca", "poco", "baja ", "faciles"):
        return "FACIL"
    if v in ("dificil", "dificiles", "alta", "alto", "duro"):
        return "DIFICIL"
    return "MEDIA"


def forwards(apps, schema_editor):
    RecetasMain = apps.get_model("AppRecetas", "RecetasMain")
    RecetasUsr = apps.get_model("AppRecetas", "RecetasUsr")
    for r in RecetasMain.objects.all():
        nuevo = normalizar(r.dificultad)
        if r.dificultad != nuevo:
            r.dificultad = nuevo
            r.save(update_fields=["dificultad"])
    for r in RecetasUsr.objects.all():
        nuevo = normalizar(r.dificultadUsr)
        if r.dificultadUsr != nuevo:
            r.dificultadUsr = nuevo
            r.save(update_fields=["dificultadUsr"])


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0012_ingredienteprecio_alter_recetasmain_dificultad_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
